### ISSUE TITLE
fix: 🤔 sd-brandshape image variant shows a distorted placeholder image

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#1239] opened 2024-08-05 08:37 UTC
## Current behavior
<img width="978" alt="Bildschirmfoto 2024-09-18 um 10 09 58" src="https://github.com/user-attachments/assets/98f39f57-571f-486b-9f84-124dcfcfa257">

## Expected behavior
<img width="1112" alt="Bildschirmfoto 2024-09-18 um 11 04 50" src="https://github.com/user-attachments/assets/f8736303-ee45-4904-b551-2e3c7eb4ee68">

## Steps to reproduce
Open Link: https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/story/components-sd-brandshape--variants

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment] 2024-09-13 08:00
@coraliefeil could you add current and expected behavior

**Comment by yoezlem** [comment] 2024-09-27 07:30
Is this not a duplicate of [#1242](https://github.com/solid-design-system/solid/issues/1242)?

**Comment by yoezlem** [comment] 2024-10-08 10:41
Duplicate of #1242. Will close this one

**Closed by yoezlem** 2024-10-08 10:41 UTC
Labels: 🔧 code
