### ISSUE TITLE
docs: 📚 Storybook Controls Don't Update UI

### ISSUE THREAD

**Issue by Vahid1919** [solid-design-system/solid#1029] opened 2024-05-03 10:00 UTC
## Description
Some controls do not reset UI changed when they are toggles. As of now, this problem only exists for the no-close-button control of sd-dialog (https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/components-sd-dialog--docs) 

Additionally the no-tail control of the sd-step also has this issue: #1007 

## Where to put the documentation
`sd-step` and `sd-dialog` docs page

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment] 2024-05-06 12:43
Edit: All input controls have this bug.

**Comment by yoezlem** [comment] 2024-05-06 12:51
Will close this one as this is not only a sd-dialog/sd-steps bug. We have this problem on very story with input fields.. so this might be a duplicate of:
https://github.com/solid-design-system/solid/issues/702
https://github.com/solid-design-system/solid/issues/898

**Closed by yoezlem** 2024-05-06 12:51 UTC
