### ISSUE TITLE
docs: 📚 split storybook into package-folder and add TOC to show available packages

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#1137] opened 2024-06-06 16:53 UTC
## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment] 2024-07-05 11:49
Duplicate of #1131

**Closed by yoezlem** 2024-07-05 11:49 UTC
Labels: documentation, Subtask
