### ISSUE TITLE
fix: 🤔 z-index sd dropdown

### ISSUE THREAD

**Issue by christophsaile** [solid-design-system/solid#534] opened 2023-11-10 11:59 UTC
## Current behavior
If you place an sd-button under a sd-dropwdown the button is above the dropdown if you open it.
![image](https://github.com/solid-design-system/solid/assets/54807480/21fa62d8-5002-4658-a6d8-4d1afb62a0d4)

Not sure if this should be the behaviour or not -> open for discussion.

## Expected behavior
Dropdown is above button?

## Steps to reproduce
![image](https://github.com/solid-design-system/solid/assets/54807480/f597b264-82f1-44b1-a284-bead813e0eec)

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by christophsaile** [comment] 2023-11-13 07:23
comparison between shoelace and sds behaviour: https://jsfiddle.net/32cLbeq0/1/.
Shoelace dropdown is above the button

**Comment by awacode21** [comment] 2024-01-05 14:39
the last month working with solid design components i experienced quite a couple of z-index issues.

I am also at the moment struggling with the same issue but with sd-select. When several sd-selects follow each other, and you open for example the first one, there is a z-index issue where the option lay underneath the following sd-select.
Might be also an issue with other form elements. i did not tested it yet.

<img width="419" alt="Bildschirmfoto 2024-01-05 um 15 29 02" src="https://github.com/solid-design-system/solid/assets/30939926/5e8408d4-feaf-4fe9-9c21-b60c56fa2d16">

**Comment by azraefendic** [comment] 2024-01-16 12:58
Just a note that the sd-dropdown was tested again with @christophsaile and it was already fixed in a later version, however the style was still missing in the sd-select so I added it there now as well.

**Comment by karlbaumhauer** [comment] 2024-01-26 14:12
> i am using latest version 2.0.0 but i am still experiencing the described issue with sd-select. This is not solved.

@azraefendic can you help out here?

**Comment by karlbaumhauer** [comment] 2024-02-08 15:41
> anything new? this is still quite a big issue

sorry for the delay. We are currently low on staff due to sick leaves and vacations. I will try to clarify asap.

**Comment by awacode21** [comment] 2024-02-09 16:43
i was able to build a reproduction and localize the problem: https://codepen.io/awacode/pen/YzgNpWm

when used within an element that is working with container query and `container-type: inline-size;` this problem exists. But you cannot change it to `container-type: size;` as this breaks the layout even worse.

**Comment by awacode21** [comment] 2024-02-09 16:55
in that case the surrounding forms are single containers with container-type: inline-size which create a new stacking context.

Currently i have no idea how to fix that case. Maybe someone else has an idea?

**Closed** 2024-02-12 09:07 UTC
Labels: 🔧 code, CL-migration
