### ISSUE TITLE
fix: 🤔 Navigation-item multiline handling

### ISSUE THREAD

**Issue by auroraVasconcelos** [solid-design-system/solid#1273] opened 2024-08-12 13:53 UTC
## Current behavior
When with multi lines, the component paddings seems off (see screenshot):
![Image](https://github.com/user-attachments/assets/2f38aa62-0860-4e44-a58c-edae471c2145)

## Expected behavior
Padding and component appreance is consistent with multi lines or single line. [Figma link](https://www.figma.com/design/lDAQh9OhtODQjx0mTzdp8A/Navigation-Item?node-id=2147-1955&t=ZKSmbdcnuy4L5RbK-4)
![Image](https://github.com/user-attachments/assets/afd448be-9cf1-44f0-b247-85e92fdf4d64)

## Steps to reproduce
Go to Navigation-item and add enough information to `default` slot to make it multilines.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by Vahid1919** [comment] 2024-09-17 12:57
Closing as I am not able to reproduce this. The current padding is consistent with Figma.
![Image](https://github.com/user-attachments/assets/cea0b9d8-1c8e-4325-959e-d365242c7147)

**Closed** 2024-09-17 12:58 UTC
Labels: 🔧 code, CL-migration
